global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'backend'
    static_configs:
      - targets: ['server-1:8080', 'server-2:8080', 'server-3:8080']